# Generated by Django 4.0.6 on 2022-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photosdefault.jpg', upload_to='profile_photos'),
        ),
    ]
